# Generated by Django 5.1.6 on 2025-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
